baseURL = "https://jordanjones.me/"
languageCode = "en-us"
title = "Jordan Jones"
theme = "PaperMod"

[params]
  description = "Professional Portfolio for Jordan Jones"
  author = "Jordan Jones"
  ShowReadingTime = true
  ShowPostNavLinks = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2